### ISSUE TITLE
Add Form Validation

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#1]
**Describe the bug**

**To Reproduce**
1. Go to Hire me.
2. press submit directly without filling any details.
3. It just reloads rather then alerting the user.

**Expected behavior**
An alert should be shown to the user that they have left the required inputs blank. 

**Screenshots**
![image](https://user-images.githubusercontent.com/78685510/192606933-1773ae63-c71d-4b8e-a413-6a077abf5332.png)

**Desktop (please complete the following information):**
 - Device Independent
 
**Smartphone (please complete the following information):**
- Device Independent

**Comment by codegoggins** [comment]
Hey ! @akashrchandran 
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help. I would like to work on this bug.

**Comment by akashrchandran** [comment]
Thanks for considering to contribute to this project. This repo is pretty beginner friendly, as its only static website. 
>

**Comment by akashrchandran** [comment]
Thanks for considering to contribute to this project. Hacktoberfest is for beginners and this repo is pretty beginner friendly.

> How exactly should I contribute to this project ? 

You can solve the issue mentioned above. It's pretty straight forward. You can [Bootstrap form validation](https://getbootstrap.com/docs/5.0/forms/validation/)

> I would like to work on this bug.

Sure you can. But wait till hacktoberfest starts that is on 1st October. After that I will assign you this issue and you can start working on it and raise a pull request after completion.

**Comment by utkarsh006** [comment]
@akashrchandran I would like to work upon this issue. Kindly assign it to me.

**Comment by akashrchandran** [comment]
@utkarsh006 someone has already asked for the issue to be assigned to them. If that person fails to complete the issue in 2-3 days then will assign it to you. You can contribute to some other issue or raise a new issue yourself. Just check the website, if you find any bugs or want to add a feature then open an issue for the same I will assign it to you if it's valid.

**Comment by akashrchandran** [comment]
@codegoggins any updates?

**Comment by codegoggins** [comment]
@akashrchandran  Still working on that , the alert issue was cleared but I am not able to reset the failed button to submit after I click OK on alert

**Comment by akashrchandran** [comment]
If you're unable to fix it, then raise a PR till what you have done. I will fix the rest.
