### ISSUE TITLE
Add social links section

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#10]
**Is your feature request related to a problem? Please describe.**
Add section for social links, between projects and bonafides.

**Describe the solution you'd like**
Just add the icons of the social media and raise PR, I will edit and add link the accounts.

**Additional context**
Be creative, if you want to or just simple works for me.

**Comment by Aman0307** [comment]
@akashrchandran I would like to contribute to this project.

**Comment by akashrchandran** [comment]
Sure. I have assigned it to you.
