### ISSUE TITLE
Change The Favicon To Black In Colour

### ISSUE THREAD

**Issue by NageshMandal** [akashrchandran/portfolio#12]
**Describe the bug**
favicoon colour is white and it is not visible
change the colour to white

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NageshMandal** [comment]
could you please assign this issue to me

**Comment by akashrchandran** [comment]
@NageshMandal I have assigned it you.
