### ISSUE TITLE
Alignment of the button is incorrect

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#15]
**Describe the bug**
The alignment of the button in mobile view is to the left , it would be better if it was center.

**To Reproduce**
1. Scroll down till Hire me.
2. And check the submit button

**Expected behavior**
The button should be centre of the screen

**Screenshots**
![IMG_20221014_161542](https://user-images.githubusercontent.com/78685510/195829497-c30b924e-9e23-42b4-870f-1b9341c5afc7.jpg)

**Desktop (please complete the following information):**
 - OS Independent

**Smartphone (please complete the following information):**
 - Device: os independent

**Additional context**
Hint: use css media queries

**Comment by albinzdaniel02** [comment]
Hi Akash ,
I would like to work on this issue if you'd assign it to me.
