### ISSUE TITLE
Progress bar animation reset fix

### ISSUE THREAD

**Issue by albinzdaniel02** [akashrchandran/portfolio#19]
***Is your feature request related to a problem? Please describe.***
A minor tweak in script.js can fix the resetting of animation of progress bars on scrolling back to the top. 

***Describe the solution you'd like***
Stopping reset animation of scroll bars.

***Describe alternatives you've considered***
Flag variable for limiting the animation to occur just once.

**Comment by akashrchandran** [comment]
Assigned to you.
