### ISSUE TITLE
Remove Carousel Arrows on mobile devices.

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#2]
**Is your feature request related to a problem? Please describe.**
There is no need for carousel arrows on mobile devices. Removing them will make it look better. 

**Describe alternatives you've considered**
As most of the mobile devices are today touch based, there is no need for arrows in mobile devices. They can be swiped to traverse through. 

**Additional context**
![IMG_20220928_083020](https://user-images.githubusercontent.com/78685510/192677743-e5801817-6de9-4380-bef6-aa175b772aea.jpg)

Just hide them in smartphones.

**Comment by sdeepanshu17** [comment]
Please assign this issue to me

**Comment by akshitsangwan** [comment]
Hey @akashrchandran, just saw your portfolio website and it looks super awesome. I assure you if given a chance, I can solve your issue and it'll be a great learning activity for me as well:)

**Comment by akshitsangwan** [comment]
Hey @akashrchandran, I have raised a PR. Kindly check and review to merge my PR. Your suggestions/feedback will be highly appreciated:)
[to solve issue #7 ](https://github.com/akashrchandran/portfolio/pull/7#issue-1392937068)

**Comment by akshitsangwan** [comment]
Hey @akashrchandran, did you check my PR??
