### ISSUE TITLE
Button animation exceeds the button size

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#21]
**Describe the bug**

Button animation after pressing submit exceed the button size.

**To Reproduce**
1. Go to Hire me
2. Fill the form
3. Press submit.

**Expected behavior**

The button should fit the content of animation.

**Screenshots**

![IMG_20221016_160601.jpg](https://user-images.githubusercontent.com/78685510/196030698-81d1e410-10cc-4c6e-9014-58cdf22f0e14.jpg)

**Desktop (please complete the following information):**
 - OS: Independent

**Smartphone (please complete the following information):**
 - OS: Independent

**Additional context**

Just increase the button size to fit everything inside.

**Comment by albinzdaniel02** [comment]
I'd like to work on this issue if you would assign it to me.
