### ISSUE TITLE
Add dynamic progress bar

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/portfolio#3]
**Is your feature request related to a problem? Please describe.**
Add dynamic progress bar using javascript. The progress bar should start from 0% and dynamically reach the given value.

**Additional context**
![IMG_20220928_164206.jpg](https://user-images.githubusercontent.com/78685510/192765754-8a4b6ad8-4744-4211-a9da-5f9bc7cab498.jpg)

**Comment by RahulSankhla312** [comment]
hey @akashrchandran developer , could you assign this issue to me.

**Comment by akashrchandran** [comment]
@RahulSankhla312 sure. Will assign it you after hacktoberfest starts. Please wait for the time being.
