### ISSUE TITLE
Update and improve readme file

### ISSUE THREAD

**Issue by sdeepanshu17** [akashrchandran/portfolio#4]
**Is your feature request related to a problem? Please describe.**
The projects lacks a proper and detailed readme file.

**Describe the solution you'd like**
Add a detailed readme file.

**Comment by akashrchandran** [comment]
sure, you can start working on it. but be sure to only raise PR after the start of hackoctoberfest.

**Comment by sdeepanshu17** [comment]
I will not be able to work on this issue, please assign this to someone else.
