### ISSUE TITLE
Touch functionality for smartphones while interacting with certificates on website

### ISSUE THREAD

**Issue by akshitsangwan** [akashrchandran/portfolio#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akshitsangwan** [comment]
Hey @akashrchandran , can you assign me this?

**Comment by akashrchandran** [comment]
assigned, you can start working on it now.

**Comment by akshitsangwan** [comment]
I have done it already on 29th Sept, just give me minute I'm raising a PR now.
Any suggestions/feedback are highly appreciated:)
P.S.: Thanks to you, I have done my very first open source contribution and I literally enjoyed it so much:)
